### ISSUE TITLE
Support for PER/UPER?

### ISSUE THREAD

**Issue by jblestang** [XAMPPRocky/rasn#105]
Any plan on adding PER/UPER encoding scheme to your nice crate?

**Comment by jblestang** [comment]
Great news!

**Comment by laf0rge** [comment]
The orignal question was for UPER.  Its great to see work in progress is happening there.  But what about APER (PER aligned variant, as used frequently in the 3GPP domain)?

**Comment by XAMPPRocky** [comment]
@laf0rge Yes, APER will be also be released at the same time, the implementation is the same as BER/CER/DER, where we have a single encoder/decoder, that changes only when the variants differ. The decoder will support basic variant of APER/UPER, and the encoder will use canonical variant.

**Comment by XAMPPRocky** [comment]
This has now been implemented and released as of 0.8.0
