### ISSUE TITLE
Encoding of default values

### ISSUE THREAD

**Issue by ERnsTL** [XAMPPRocky/rasn#110]
Greetings, I have played with ASN.1 encoding and got a schema with a DEFAULT value.

In rasn this is done with 

```
struct Test {
  #[rasn(default = True)]
  friendly bool
}
```

Current behavior:

But when I encode using ber or der, it still gets serialized according to PDU analyzer and the file size does not change.

Expected behavior:

At the least with DER, if the Rust struct is set to the default value (in above case True), then the default value is redundant and it should not be in the serialized output - if I understand this [https://www.oss.com/asn1/knowledge-center/asn1-tools-general/is-default-optional-or-mandatory.html](resource from OSS) correctly.

I can post a minimum working example.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I believe the above example is incorrect, the default parameter should point to a function.

**Comment by ERnsTL** [comment]
That works nicely now - Thanks for the pointer!

![Bildschirmfoto vom 2022-11-08 23-48-31](https://user-images.githubusercontent.com/80753686/200692909-09994efe-ebb2-409e-86bc-c5e80be0317c.png)
