### ISSUE TITLE
release version to pickup fix from issue #97

### ISSUE THREAD

**Issue by pschoenm** [XAMPPRocky/rasn#113]
Can you please release a new version include the fix for issue #97 .  I would prefer to pick up the code from crates.io rather than git directly.

**Comment by allaouiamine** [comment]
Hello,
Is it already released? I can still see v0.6.0 as the latest in crates.io

**Comment by XAMPPRocky** [comment]
No sorry, I haven't done so yet. I've been focused on the PER implementation in the `per` branch. I'll release it today.

**Comment by XAMPPRocky** [comment]
I've now released 0.7.0 with the latest fixes
