### ISSUE TITLE
[snmp] All fields are private?

### ISSUE THREAD

**Issue by repnop** [XAMPPRocky/rasn#14]
Hi, a friend just linked your 0.3.0 announcement and I'm super excited to see SNMP stuff get a crate! :D However, reading through the docs and then the code, I'm assuming some fields were forgotten to be made `pub`? e.g. https://github.com/XAMPPRocky/rasn/blob/fb424b886f15d2d3943fffbb72ae0d2fccdf4e7b/standards/snmp/src/v1.rs#L52-L58

There's no way to construct or inspect any `Pdu` since all fields are private and there's no constructor or accessor methods. Seems like the other structs have similar issues. Haven't looked at the other new crates yet so not sure if its the case there either.

**Comment by XAMPPRocky** [comment]
Whoops minor mistake, I'll release a patch with public fields.
