### ISSUE TITLE
Error with .map_err(error::map_nom_err)?; at several places

### ISSUE THREAD

**Issue by sivizius** [XAMPPRocky/rasn#2]
E.g. at `/src/ber/de.rs:60:70` I get the error:
```
    --> /home/sivizius/.cargo/registry/src/github.com-1ecc6299db9ec823/rasn-0.2.0/src/ber/de.rs:60:70
   |
60 |             self::parser::parse_identifier_octet(self.input).map_err(error::map_nom_err)?;
   |                                                                      ^^^^^^^^^^^^^^^^^^ expected signature of `fn(nom::Err<nom::error::Error<&[u8]>>) -> _`
   | 
  ::: /home/sivizius/.cargo/registry/src/github.com-1ecc6299db9ec823/rasn-0.2.0/src/ber/de/error.rs:20:1
   |
20 | pub(crate) fn map_nom_err(error: nom::Err<(&[u8], nom::error::ErrorKind)>) -> Error {
   | ----------------------------------------------------------------------------------- found signature of `for<'r> fn(nom::Err<(&'r [u8], nom::error::ErrorKind)>) -> _`
```
similar errors at other places, where `.map_err(error::map_nom_err)?` is used.

**Comment by sivizius** [comment]
Apparently it works just fine with nom 1.5.2, but fails with any alpha-version. I guess, changing back to nom 1.5.2 until this issue is resolved, is the best solution for now? Or does something else break then?

**Comment by XAMPPRocky** [comment]
Yeah, the problem is you're using two incompatible versions of nom. When the new mom is released I will update it, otherwise you can use the older nom for now, or fork/clone a copy of the project for yourself and change the nom version there and use that in the meantime.
