### ISSUE TITLE
Optional Choice causing errors

### ISSUE THREAD

**Issue by anthok** [XAMPPRocky/rasn#25]
Unit test that shows error

Error : ```Custom { msg: "Encoding field of type `OptionalChoice`: CHOICE-style enums do not allow implicit tagging. If using the derive macro on a sequence with a choice field ensure it is marked with `#[rasn(choice)]`."```

```
use rasn::{types::*, Decode, Encode};

#[derive(AsnType, Decode, Encode, Debug, PartialEq, Clone)]
pub struct OptionTest {
    #[rasn(tag(0))]
    pub regular: rasn::types::Integer,

    #[rasn(tag(1))]
    pub optional: Option<OptionalChoice>,
}

#[derive(AsnType, Decode, Encode, Debug, PartialEq, Clone)]
#[rasn(choice)]
pub enum OptionalChoice {
    #[rasn(tag(0))]
    Test(rasn::types::Integer),
}

#[test]
fn it_works() {
    let data = OptionTest {
        regular: 0.into(),
        optional: Some(OptionalChoice::Test(0.into())),
    };
    let bin = rasn::ber::encode(&data).unwrap();
    assert_eq!(data, rasn::ber::decode(&bin).unwrap());
}

```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I have a question that I'd like your opinion on. Would it be more intuitive for `decode_with_tag` to always fail for `CHOICE` types (as it does today), or have it work, but it always explicitly tags the encoding? So `decode_with_tag` will not always mean "implicitly tag this value", but it would remove this issue entirely.

**Comment by anthok** [comment]
I'm not sure and I would say I don't fully understand the consequences of choosing one way over the other. Sorry!

**Comment by XAMPPRocky** [comment]
Okay, well I implemented it anyway, and we'll see what people think, this code should work, and you should no longer need to use `#[rasn(choice)]` on fields at all, it will just figure it out.

**Comment by anthok** [comment]
So it is working if I leave in the `#[rasn(choice)]` but removing it causes some errors. Is it still needed on the enum?

**Comment by XAMPPRocky** [comment]
Yes, you still need to define it on the enum. You don't need it on fields where you use that enum, it will do nothing so having it should have no effect.
