### ISSUE TITLE
Implicit string value is private

### ISSUE THREAD

**Issue by anthok** [XAMPPRocky/rasn#28]
When you have a Implicit string like below, it's not possible to access the value by itself because value is private.
`Implicit { _tag: PhantomData, value: "TestString" }`

```
error[E0616]: field `value` of struct `Implicit` is private
    |             println!("{:?}", obj.value);
    |                                  ^^^^^ private field

```

**Comment by XAMPPRocky** [comment]
Thank you for your issue! If you'd like I'd accept a PR making the field `pub`.
