### ISSUE TITLE
Problem parsing and encoding Option for CHOICE

### ISSUE THREAD

**Issue by Albibek** [XAMPPRocky/rasn#32]
Hi.

I am trying to follow the RFC5280 [section](https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.13) for CRL distribution point certificate extension

```
GeneralName ::= CHOICE {
     otherName                 [0]  AnotherName,
     rfc822Name                [1]  IA5String,
     dNSName                   [2]  IA5String,
     x400Address               [3]  ORAddress,
     directoryName             [4]  Name,
     ediPartyName              [5]  EDIPartyName,
     uniformResourceIdentifier [6]  IA5String,
     iPAddress                 [7]  OCTET STRING,
     registeredID              [8]  OBJECT IDENTIFIER }
     
  CRLDistributionPoints ::= SEQUENCE SIZE (1..MAX) OF DistributionPoint

   DistributionPoint ::= SEQUENCE {
        distributionPoint       [0]     DistributionPointName OPTIONAL,
        reasons                 [1]     ReasonFlags OPTIONAL,
        cRLIssuer               [2]     GeneralNames OPTIONAL }

   DistributionPointName ::= CHOICE {
        fullName                [0]     GeneralNames,
        nameRelativeToCRLIssuer [1]     RelativeDistinguishedName }   
 ```
 
 I've only implemented a basic part of it and trying to parse the extension field from a [well-known CA certificate](https://cacerts.digicert.com/DigiCertAssuredIDTLSCA.crt.pem)
 
 Here's my code: https://gist.github.com/Albibek/bdfaa3464ac7b8f009865b3426164a68
 I'm using the main branch of the library since Option does not work in 0.3 at all giving a macro error. 
 
 I see two problems: 
 * decoding does not work when I specify an Option<...> field, but starts working with a non-optional field
 * encoding of the same data does not give the same result, giving the wrong tags(0x80 instead of 0x0a) and strings lengths (0x74 instead of 0x78 for the very first sequence)
 
 It is still probably me using the library wrong but can also be it's some problems with the library. 
 
 Thanks in advance.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'll look into this, I remember not being completely happy with how I implemented options, so it could be wrong.

**Comment by XAMPPRocky** [comment]
@Albibek Okay, I believe I've fixed the issue, though to be honest I couldn't ever get your example to fail to run, so I might have been missing something.

**Comment by Albibek** [comment]
Yep, sorry I didn't add asserts initialls, was just analysing visually. I can see now that the structure is parsed, but encoding the same structure back does not give the same byte string in the second test.

I may be wrong, but it seems that the tag becomes explicit somehow. I've fixed the gist to contain the assertion, so you could get a better view on it.

**Comment by XAMPPRocky** [comment]
I'm still debugging it, but this is the exact diff between the two at the moment, using `pretty-assertions`.

```diff
Diff < left / right > :
 [
     48,
<    114,
>    120,
     48,
<    112,
<    128,
<    110,
>    58,
     160,
<    108,
>    56,
>    160,
>    54,
     134,
     52,
     104,
```

**Comment by XAMPPRocky** [comment]
Hmm, could you clarify what version of the module you're using? there's one with explicit tags and one with implicit tags, and that would be relevant to how we encode this.

**Comment by Albibek** [comment]
> Hmm, could you clarify what version of the module you're using? there's one with explicit tags and one with implicit tags, and that would be relevant to how we encode this.

Not sure what do you mean by this. In Cargo.toml I'm importing only main branch of rasn

```
rasn = { git = "https://github.com/XAMPPRocky/rasn.git", branch = "main" }
```

And then, in .rs file I import everything as 
```
use rasn::{de::Decode, types::*, *};
```

Am I missing some options allowing me to specify which tags to use?

**Comment by XAMPPRocky** [comment]
> Not sure what do you mean by this.

RFC5280 contains two ASN.1 modules, one with [`EXPLICIT TAGS`](https://datatracker.ietf.org/doc/html/rfc5280#appendix-A.1) and another with [`IMPLICIT TAGS`](https://datatracker.ietf.org/doc/html/rfc5280#appendix-A.2). Whichever one you use would change how you'd structure the `rasn` data structures.

**Comment by Albibek** [comment]
This particular spec which I have problem with is all encoded using implicit tags. You can find the GeneralName spec on the top of page 127 and DistributionPoints related specs at the bottom of page 128. They are all in Apendix A.2, so the tags are implicit.

**Comment by XAMPPRocky** [comment]
Alright, I've now both implemented `SET` encoding/decoding, and to test that everything would work as expected, I actually implemented RFC 5280 myself. It's available under `standards/pkix`. Check it out, and I will release it in a couple of days, once I've added documentation and written release notes.

**Comment by Albibek** [comment]
Wow, that is really cool, thank you, it works now!  I can now migrate to using your library in my whole solution. 

Also had to fix an error in my test: the certificate apparently had a list of distribution points instead of one point with the list of names.  I've updated the gist for historical reasons.
