### ISSUE TITLE
asn message with choice and tag is not encoded  correctly

### ISSUE THREAD

**Issue by yaozongyou** [XAMPPRocky/rasn#35]
hello, here is my asn file:

```bash
World-Schema DEFINITIONS AUTOMATIC TAGS ::= 
BEGIN
Request ::= SEQUENCE {
  num INTEGER
}
Response ::= SEQUENCE {
  ret INTEGER
}     
BODY ::= CHOICE { 
  request [3000] Request,
  response [3001] Response
}                 
Message ::= SEQUENCE {
  id   INTEGER, 
  body BODY
}                              
END
```

and message with value
```bash
value Message ::= {
  id 1,
  body request : {
    num 1
  }
}
```

I have tested this on https://asn1.io/asn1playground/Default.aspx and the message is encoded as:
`0101BF9738   0101`

here is my rust code using rasn
```rust
use rasn::AsnType;
use rasn::Decode;
use rasn::Encode;
use std::error::Error;

#[derive(Debug, AsnType, Decode, Encode)]
struct Message {
    id: i32,
    #[rasn(choice)]
    body: BODY,
}

#[derive(Debug, AsnType, Decode, Encode)]
#[rasn(choice)]
enum BODY {
    #[rasn(tag(context, 3000))]
    Request(Request),

    #[rasn(tag(context, 3001))]
    Response(Response),
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Request {
    num: i32,
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Response {
    ret: i32,
}

fn main() -> Result<(), Box<dyn Error>> {
    let p = Message {
        id: 1,
        body: BODY::Request(Request { num: 1 }),
    };
    let e = rasn::der::encode(&p).unwrap();
    println!("e: {:#04x?}", e);
    Ok(())
}
```

and it outputs 
`0x30,0x0a,0x02,0x01,0x01,0xbf,0xb8,0x17,0x03,0x02,0x01,0x01,`

the big difference is the body choice on https://asn1.io/asn1playground/Default.aspx is decoded as `BF9738` but using rasn decoded as `BFB817`.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I've now addressed this on `main`.

**Comment by yaozongyou** [comment]
@XAMPPRocky I think there is still some mistakes.

```rust
use rasn::AsnType;
use rasn::Decode;
use rasn::Encode;
use std::error::Error;

#[derive(Debug, AsnType, Decode, Encode)]
struct Message {
    id: i32,
    #[rasn(choice)]
    body: BODY,
}

#[derive(Debug, AsnType, Decode, Encode)]
#[rasn(choice)]
enum BODY {
    #[rasn(tag(context, 3000))]
    Request(Request),

    #[rasn(tag(context, 3001))]
    Response(Response),
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Request {
    num: i32,
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Response {
    ret: i32,
}

fn main() -> Result<(), Box<dyn Error>> {
    let p = Message {
        id: 1,
        body: BODY::Request(Request { num: 1 }),
    };
    let e = rasn::der::encode(&p).unwrap();
    println!("e: {:#04x?}", e);
    Ok(())
}
```
the above code prints `0x30,0x0a,0x02,0x01,0x01,0xbf,0xb8,0x17,0x03,0x02,0x01,0x01`

but it should prints`0x30,0x0a,0x02,0x01,0x01,0xbf,0x97,0x38,0x03,0x02,0x01,0x01`

**Comment by yaozongyou** [comment]
@XAMPPRocky I think there is still some mistakes.


```rush
use rasn::AsnType;
use rasn::Decode;
use rasn::Encode;
use std::error::Error;


#[derive(Debug, AsnType, Decode, Encode)]
struct Message {
&nbsp; &nbsp; id: i32,
&nbsp; &nbsp; #[rasn(choice)]
&nbsp; &nbsp; body: BODY,
}


#[derive(Debug, AsnType, Decode, Encode)]
#[rasn(choice)]
enum BODY {
&nbsp; &nbsp; #[rasn(tag(context, 3000))]
&nbsp; &nbsp; Request(Request),


&nbsp; &nbsp; #[rasn(tag(context, 3001))]
&nbsp; &nbsp; Response(Response),
}


#[derive(Debug, AsnType, Decode, Encode)]
struct Request {
&nbsp; &nbsp; num: i32,
}


#[derive(Debug, AsnType, Decode, Encode)]
struct Response {
&nbsp; &nbsp; ret: i32,
}


fn main() -&gt; Result<(), Box<dyn Error&gt;&gt; {
&nbsp; &nbsp; let p = Message {
&nbsp; &nbsp; &nbsp; &nbsp; id: 1,
&nbsp; &nbsp; &nbsp; &nbsp; body: BODY::Request(Request { num: 1 }),
&nbsp; &nbsp; };
&nbsp; &nbsp; let e = rasn::der::encode(&amp;p).unwrap();
&nbsp; &nbsp; println!("e: {:#04x?}", e);
&nbsp; &nbsp; Ok(())
}
```
the above code prints `0x30,0x0a,0x02,0x01,0x01,0xbf,0xb8,0x17,0x03,0x02,0x01,0x01`


but it should prints`0x30,0x0a,0x02,0x01,0x01,0xbf,0x97,0x38,0x03,0x02,0x01,0x01`







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 晚上11:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XAMPPRocky/rasn] asn message with choice and tag is not encoded  correctly (#35)





 
Thank you for your issue! I've now addressed this on main.
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yaozongyou** [comment]
@XAMPPRocky I have added `#[rasn(automatic_tags)]` as in `tests/issue35.rs`, but the output is `0xb8,0x17` which is not i wanted.
`0xb8,0x17` as in binary is `1011100000010111` which is high-tag-nubmer form of 7191.  the output should be `0x97,0x38` which in binary is `1001011100111000`  which is high-tag-number form of 3000, and this is right.

**Comment by XAMPPRocky** [comment]
Thank you for updating it, I've now fixed that issue as well.

**Comment by yaozongyou** [comment]
thanks, it works as expected.
