### ISSUE TITLE
support explicitly tagged types encoding

### ISSUE THREAD

**Issue by yaozongyou** [XAMPPRocky/rasn#36]
```rust
use rasn::{AsnType,Decode,Encode};
use std::error::Error;

#[derive(Debug, AsnType, Decode, Encode)]
struct Message {
    id: i32,
    #[rasn(choice, enumerated)]
    body: BODY,
}

#[derive(Debug, AsnType, Decode, Encode)]
#[rasn(choice)]
enum BODY {
    #[rasn(tag(context, 3000))]
    Request(Request),

    #[rasn(tag(context, 3001))]
    Response(Response),
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Request {
    num: i32,
}

#[derive(Debug, AsnType, Decode, Encode)]
struct Response {
    ret: i32,
}

fn main() -> Result<(), Box<dyn Error>> {
    let p = Message {
        id: 1,
        body: BODY::Request(Request { num: 1 }),
    };
    let e = rasn::der::encode(&p).unwrap();
    println!("e: {:02x?}", e);
    Ok(())
}
```
the above piece of code prints: `30, 0a, 02, 01, 01, bf, 97, 38, 03, 02, 01, 01`
i want it to print  `30, 0c, 02, 01, 01, bf, 97, 38, 05, 30, 03, 02, 01, 01`  because it need to talk to some program written using c++ and golang. This encoding requires each CHOICE of BODY explicitly tagged. See 5.2 Explicitly tagged types of http://luca.ntop.org/Teaching/Appunti/asn1.html
Is it possible to achieve this?

**Comment by XAMPPRocky** [comment]
> Is it possible to achieve this?

Yes, but not currently through the macro. (I'm adding it soon). For now, you have to use the `Explicit` new type wrapper, or write codec implementation yourself and call `Encoder::encode_explicit_prefix`/`Decoder::decode_explicit_prefix`.

```rust
struct Body;

struct C0;

impl AsnType for C0 {
    const TAG: rasn::Tag = rasn::Tag::new(rasn::types::Context, 0);
}

type WrappedBody = Explicit<C0, Body>;

let body = WrappedBody(Body);

assert_eq!(body, rasn::ber::decode(&rasn::ber::encode(&body).unwrap()).unwrap());
```

**Comment by yaozongyou** [comment]
Thanks for your reply, I will have a try with the Explicit new type wrapper.

**Comment by XAMPPRocky** [comment]
This is now available in the macro by using `explicit` around your tag definition. E.g. `#[rasn(tag(explicit(context, 3000)))]`
