### ISSUE TITLE
How to deal with CHOICE-style enums do not allow implicit tagging.

### ISSUE THREAD

**Issue by messense** [XAMPPRocky/rasn#4]
```rust
use rasn::{types::*, *};

#[test]
fn choice() {
    #[derive(AsnType, Clone, Debug, Encode, Decode, PartialEq)]
    struct ChoiceField {
        choice: VecChoice,
    }

    #[derive(AsnType, Clone, Debug, Decode, Encode, PartialEq)]
    #[rasn(choice)]
    enum VecChoice {
        #[rasn(tag(1))]
        Bar(Vec<bool>),
        #[rasn(tag(2))]
        Foo(Vec<OctetString>),
    }
    let bar = ChoiceField { choice: VecChoice::Bar(vec![true]) };
    let foo = ChoiceField { choice: VecChoice::Foo(vec![OctetString::from(vec![1, 2, 3, 4, 5])]) };
    assert_eq!(foo, ber::decode(&ber::encode(&foo).unwrap()).unwrap());
    assert_eq!(bar, ber::decode(&ber::encode(&bar).unwrap()).unwrap());
}
```

errors with thread 'choice' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { msg: "CHOICE-style enums do not allow implicit tagging." }', tests/derive.rs:67:52

if impl Decode manually for ChoiceField:

```rust
use rasn::{types::*, *};

#[derive(AsnType, Clone, Debug, Encode, PartialEq)]
    struct ChoiceField {
        choice: VecChoice,
    }

    impl Decode for ChoiceField {
        fn decode_with_tag<D: rasn::Decoder>(decoder: &mut D, tag: Tag) -> Result<Self, D::Error> {
            let mut decoder = decoder.decode_sequence(tag)?;
            Ok(Self {
                choice: <_>::decode(&mut decoder)?,
            })
        }
    }

    #[derive(AsnType, Clone, Debug, Decode, Encode, PartialEq)]
    #[rasn(choice)]
    enum VecChoice {
        #[rasn(tag(1))]
        Bar(Vec<bool>),
        #[rasn(tag(2))]
        Foo(Vec<OctetString>),
    }
    let bar = ChoiceField { choice: VecChoice::Bar(vec![true]) };
    let foo = ChoiceField { choice: VecChoice::Foo(vec![OctetString::from(vec![1, 2, 3, 4, 5])]) };
    assert_eq!(foo, ber::decode(&ber::encode(&foo).unwrap()).unwrap());
    assert_eq!(bar, ber::decode(&ber::encode(&bar).unwrap()).unwrap());
```

then it errors with thread 'choice' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { msg: "CHOICE-style enums do not allow implicit tagging." }', tests/derive.rs:66:52

So what's the proper way to deal with it? Thanks!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This is actually a bug in the struct decode derive. You can [see in the code](https://github.com/XAMPPRocky/rasn/blob/main/macros/src/decode.rs#L19) that it always calls `decode_with_tag`, which it shouldn't for `CHOICE`. I think to address this there probably needs to be a new `#[rasn(choice)]` attribute that tells the derive to not use `decode_with_tag`. In the meantime you can fix it will a manual `Decode` & `Encode` implementation.

I don't know why the second example is failing. Would you be able to run `cargo-expand` (you need to install it if you don't have it already) and show the output? there shouldn't be an issue with that.

**Comment by messense** [comment]
The second example is failing because `encode` is calling `encode_with_tag`, it also fails with choice, manual Encode impl fixes it.
