### ISSUE TITLE
rasn-kerberos: explicit tagging

### ISSUE THREAD

**Issue by x-delfino** [XAMPPRocky/rasn#69]
Thanks for the great library. 

I’m trying to use the rasn_kerberos structures but am having some issues. I’m by no means an expert here, so may be doing something wrong.

Specifically, if I’m building an AS-REQ - which is defined in [RFC 4120](https://datatracker.ietf.org/doc/html/rfc4120#appendix-A) as follows:

```
AS-REQ          ::= [APPLICATION 10] KDC-REQ
KDC-REQ         ::= SEQUENCE {
        -- NOTE: first tag is [1], not [0]
        pvno            [1] INTEGER (5) ,
        msg-type        [2] INTEGER (10 -- AS -- | 12 -- TGS --),
        padata          [3] SEQUENCE OF PA-DATA OPTIONAL
                            -- NOTE: not empty --,
        req-body        [4] KDC-REQ-BODY
} 
```

The rasn generated der encoded value starts:
`6A, 81, 9D, 81, 01, 05 …`

With 6A representing the application tag of 10, and 81, 9D representing the length. However I would be expecting a sequence tag next (30).

Based on this - I believe that implicit tagging is being used here? 

As per [RFC 4120](https://datatracker.ietf.org/doc/html/rfc4120#section-5), explicit tagging should be used: 
```
   The type definitions in this section assume an ASN.1 module
   definition of the following form:

   KerberosV5Spec2 {
           iso(1) identified-organization(3) dod(6) internet(1)
           security(5) kerberosV5(2) modules(4) krb5spec2(2)
   } DEFINITIONS EXPLICIT TAGS ::= BEGIN

   -- rest of definitions here

   END

   This specifies that the tagging context for the module will be
   explicit and non-automatic.
```

If I compare the rasn generated encoding with a functioning AS-REQ that I’ve captured (bare in mind different size), it includes the tag and length for the sequence (30, 81, DC) as well as for the Integer (02, 01)

`6A, 81, DF, 30, 81, DC, A1, 03, 02, 01, 05 …`

I note from https://github.com/XAMPPRocky/rasn/issues/36 that explicit tagging is available via the macro now. This seems to have worked fine for the fields, but I can’t figure out how one would set the application tag as explicit.

`#[rasn(tag(explicit(application, 11)), delegate)]`

Panics with:

``the `#[rasn(tag)]` attribute must be a list``

I would appreciate your thoughts - apologies if I’m incorrect with my assessment here

**Comment by XAMPPRocky** [comment]
Thank you for your issue! That panic looks like a bug to me, that syntax should work.

**Comment by x-delfino** [comment]
I've done a little further testing - I was able to set a context-specific tag on the asreq with: 
`#[rasn(tag(explicit(11)), delegate)]`
However that outputs
`AB, 81, 9F, A1, 03, 02, 01, 05 ...`

Whilst it has added the tag (AB, 81, 9F), it seems to have done it implicitly - as I would expect the Sequence tag next instead of the tags for the first field (A1, 03, 02, 01). I'm not sure if the 'delegate' option is relevant here - I don't really know how that works yet.

The usage of a context-specific tag was just for testing purposes as it didn't cause a panic like the application tags were - but hopefully helps

**Comment by XAMPPRocky** [comment]
The delegate attribute essentially means "Use the inner type for everything", it allows you to easily have newtype wrappers that are identical to their inner type.

Imagine you have ASN.1 like the following:

```asn1
MyInt ::= INTEGER;
```

You could write that in Rasn as a type alias, but Type aliases in rust are pretty weak, they don't allow you add methods or trait implementations. With `delegate` we essentially have aliased types in ASN.1 but newtype wrappers in Rust, allowing us to add methods and trait definitions as we like. The other thing it allows us to do is have a aliased type with a different Tag than the original.

```rust
// Without `delegate`
type MyInt = rasn::types::Integer;

// With delegate
#[rasn(delegate)]
struct MyInt(pub rasn::types::Integer);
```

**Comment by XAMPPRocky** [comment]
@x-delfino I've now pushed up a fix for the explicit tag parsing so `#[rasn(tag(explicit(application, 11)))]` now works.

**Comment by x-delfino** [comment]
nice one - thanks for sorting that so quickly and for the explanation of delegate. I can confirm that it's now not panicking with explicit application tagging. 

However, it seems to be still tagging implicitly for structs when I would expect a SEQUENCE tag to be present.

If I set the tagging on the AsReq with: `#[rasn(tag(explicit(application, 10)), delegate)]`

That produces a result of: `6A, 81, 9F, A1, 03, 02, 01, 05`

We've got the application tag and length of `6A, 81, 9F`, then straight to the first field's tags `A1, 03 ...`

For testing purposes, I removed AsReq from the equation and set the application tag directly on the KdcReq with: `#[rasn(tag(explicit(application, 10))]` and observed the same output.

And just to confirm, I observed the same issue when trying to explicitly tag the struct with a context specific tag

**Comment by XAMPPRocky** [comment]
I've now fixed that, and fixed explicit tagging in the Kerberos library. Thank you again for your issue! Want to try it out, and if it's working for you I can put out a patch release.

**Comment by x-delfino** [comment]
Amazing - thank you. Not quite working for me still, I’m now seeing:
`30, 81, E2, 30, 81, DF, A1, 03, 02, 01, 05`

We seem to have two SEQUENCE tags now (`30, 81, E2, 30, 81, DF`) but no application tag, followed by the first field (`A1, 03, 02, 01, 05`)

**Comment by XAMPPRocky** [comment]
Can you provide a full example, because in my test here, I can see the application tag.

https://github.com/XAMPPRocky/rasn/blob/9051ed6a3d494c00e634c2111eed550dd510a2da/tests/explicit_delegate.rs#L3-L19

**Comment by x-delfino** [comment]
Sure thing
```
    let as_req = AsReq(KdcReq {
        pvno: Integer::parse_bytes(b"5", 10).unwrap(),
        msg_type: Integer::parse_bytes(b"10", 10).unwrap(),
        padata: None,
        req_body: KdcReqBody {
            kdc_options: KdcOptions(
                KerberosFlags::from_vec(vec!(0;4))
            ),
            cname: None,
            realm: KerberosString::new("COMPANY.INT".to_string()),
            sname: None,
            from: None,
            till: KerberosTime(DateTime::parse_from_rfc2822("Fri, 04 Feb 2022 10:11:11 GMT").unwrap()),
            rtime: None,
            nonce: 123514514,
            etype: vec![18],
            addresses: None,
            enc_authorization_data: None,
            additional_tickets: None,
        }
    });
    println!("{:02X?}", der::encode(&as_req).unwrap());
```

Produces an output starting with `30, 55, 30, 53, A1, 03, 02, 01, 05`

**Comment by XAMPPRocky** [comment]
@x-delfino Alright, I think I've pushed up a fix for that, do you want to give it another shot?

**Comment by x-delfino** [comment]
Nice one - thank you @XAMPPRocky, that looks to be working correctly now, with my above example now outputting
`6A, 55, 30, 53, A1, 03, 02, 01, 05 ...`

Thank you for your work in getting this resolved and for the library in general
