### ISSUE TITLE
rasn-kerberos: Optional but not Empty

### ISSUE THREAD

**Issue by x-delfino** [XAMPPRocky/rasn#70]
In the Kerberos Spec ([RFC 4120](https://datatracker.ietf.org/doc/html/rfc4120#appendix-A)) - there are a few instances of OPTIONAL fields that cannot be empty, eg. `padata`:
```
KDC-REQ         ::= SEQUENCE {
        -- NOTE: first tag is [1], not [0]
        pvno            [1] INTEGER (5) ,
        msg-type        [2] INTEGER (10 -- AS -- | 12 -- TGS --),
        padata          [3] SEQUENCE OF PA-DATA OPTIONAL
                            -- NOTE: not empty --,
        req-body        [4] KDC-REQ-BODY
}
```

In the rasn implementation, it looks like `OPTIONAL` fields with a `None` value are added with zero-length instead of being omitted.

Eg, if we look at the encoding of:

```
KDC-REQ         ::= SEQUENCE {
        pvno            [1] INTEGER = 5,
        msg-type        [2] INTEGER = 10,
        padata          [3] SEQUENCE OF PA-DATA = None,
        req-body        [4] KDC-REQ-BODY = ...
}
```

We get `30, 81, DF, A1, 03, 02, 01, 05, A2, 03, 02, 01, 0A, A3, 00, A4 ...` (bear in mind that I've changed the context-specific tags in rasn-kerberos to explicit as per conversation in https://github.com/XAMPPRocky/rasn/issues/69). Breaking that down for clarity:

```
30, 81, DF = KDC-REQ tag & length,
A1, 03, 02, 01, 05 = pvno,
A2, 03, 02, 01, 0A = msg-type,
A3, 00 = padata (SHOULD BE OMITTED),
A4 ... = req-body
``` 

Additionally, it seems like the Windows kerberos implementation doesn't like empty `OPTIONAL` fields even if they're not marked as such in the RFC eg. some of the time fields.

```
        from                    [4] KerberosTime OPTIONAL,
        till                    [5] KerberosTime,
        rtime                   [6] KerberosTime OPTIONAL,
```

Is there functionality within rasn to support this scenario? Let me know if there are any other details that would be helpful here.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I believe this one should be fixed now. Want to try the latest main and let me know?

**Comment by x-delfino** [comment]
awesome - looks like that's working now and I have valid as-reqs :) i've extended the test to a full valid message in https://github.com/XAMPPRocky/rasn/pull/75
