### ISSUE TITLE
`Oid` is const constructable since Rust 1.58.0

### ISSUE THREAD

**Issue by repnop** [XAMPPRocky/rasn#71]
Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3f86d7648af09a1fb561b0c510fe0c9e

I didn't notice any MSRV policy, but if you're not concerned with supporting older Rust versions, `ConstOid` can be removed and replaced with `const` associated functions on `Oid` now 🎉 `Option::unwrap` still isn't `const` however its trivial to create a function to do the same thing as shown in the playground link, so I don't think that's really a blocker since its on the user's end.

**Comment by repnop** [comment]
@XAMPPRocky what would you like done with `ConstOid` in a PR for this? the `oids!` macro currently creates `ConstOid`s, so changing those over would currently be a breaking change, but if that's going to happen I think that completely removing the type might as well happen at the same time since the version would need bumped anyway, but alternatively could leave it and the macro alone right now and simply `#[deprecate(...)]` `ConstOid` to start moving people over

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Sorry not replying. I would welcome a PR that moves everything over to `Oid`.
