### ISSUE TITLE
`rasn_snmp::v2::IpAddress` allows for !=4 byte IPs whereas the RFC does not

### ISSUE THREAD

**Issue by repnop** [XAMPPRocky/rasn#73]
[Section 3](https://datatracker.ietf.org/doc/html/rfc3416#section-3) of the [Version 2 of the Protocol Operations for the Simple Network Management Protocol (SNMP)](https://datatracker.ietf.org/doc/html/rfc3416) RFC specifies `IpAddress` as the following:
`IpAddress ::= [APPLICATION 0] IMPLICIT OCTET STRING (SIZE (4))` which only allows 4-byte IPv4 addresses, whereas `rasn_snmp::v2::IpAddress` allows for arbitrarily sized, malformed IPs:
```rust
#[test]
fn bad_ip_address() {
    let ip = IpAddress {
        0: OctetString::from_static(&[255, 255, 255]),
    };
    assert_eq!(
        rasn::ber::decode::<IpAddress>(&rasn::ber::encode(&ip).unwrap()).unwrap(),
        ip
    );
}
```

Also unrelated, but I think the type alias for `rasn_smi::v2::Integer32` is incorrect as well, its currently:
```rust
pub type Integer32 = u32;
```
but I think it should be
```rust
pub type Integer32 = i32;
```
since the unsigned 32-bit integer type is already covered by `Gauge` and by type alias `Unsigned32`

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This is a known limitation currently. Rasn only guarantees that the type is a valid ASN.1 message, and doesn't do any checks for constraints, so you can receive semantically invalid messages. This will be fixed with the addition PER which requires constraints in the codec framework in order to properly encode.

**Comment by fhhowdy** [comment]
Any update to this?  I've got several message types that are encoded with various lengths of OctetString.  The specific lengths are causing the BER decoding to fail.  If you can point me in the right directly, I can see if I can do a pull request.
