### ISSUE TITLE
SetOf without sorting

### ISSUE THREAD

**Issue by makavity** [XAMPPRocky/rasn#83]
Hello!
In my project, I faced with some suspicious behaviour SetOf decoding.

I have correct cms structure, and I'm trying to get SignerInfo.signed_attrs as bytes.
[CMS Structure decoded correctly](https://lapo.it/asn1js/#MIIFlQYJKoZIhvcNAQcCoIIFhjCCBYICAQExDzANBgkqcAACACJlH1EFADAQBgkqhkiG9w0BBwGgAwQBQaCCA9MwggPPMIIDiaADAgECAgxA5YlSkJGDogAA9xgwDQYJKnAAAgAiZS0MBQAwgasxOzA5BgNVBAMeMgQgBDUEQQQ_BEMEMQQ7BDgEOgQwBD0EQQQ6BDgEOQAgBCMEJgAgACgEQgQ1BEEEQgApMV0wWwYDVQQKHlQEIAQjBB8AIAAiBB0EMARGBDgEPgQ9BDAEOwRMBD0ESwQ5ACAERgQ1BD0EQgRAACAETQQ7BDUEOgRCBEAEPgQ9BD0ESwRFACAEQwRBBDsEQwQzACIxDTALBgNVBAYeBABCAFkwHhcNMjAxMDAyMTA1NTI0WhcNMjIxMDAyMjA1OTU5WjCBjTELMAkGA1UEBgwCQlkxEjAQBgNVBAUMCUFBODY0MzQ2NjEVMBMGA1UEBAwM0KLQldCh0KLQntCSMRUwEwYDVQQpDAzQodCV0KDQk9CV0JkxHzAdBgNVBCoMFtCT0JXQndCd0JDQlNCs0JXQktCY0KcxGzAZBgNVBAMMElNFUkdFSSBHUklTSEtPVkVUUzBdMBgGCipwAAIAImUtAgEGCipwAAIAImUtAwEDQQAYHvNFMV5A6T3Bk_Q4kUhNhrd2Ux_h4jwVUqjwIDbchBxBSX-ogT-obOvbczrAIZIw1--LMTmCI8zEGqGljbn5o4IBpjCCAaIwHwYDVR0jBBgwFoAU1J_YfkmYoODPfkzHuOthdSTEz7YwCQYDVR0TBAIwADAtBgNVHR8EJjAkMCKgIKAehhxodHRwOi8vY3JsLW9jc3Avc3ViY2FSVUMuY3JsMGcGCCsGAQUFBwEBBFswWTArBggrBgEFBQcwAYYfaHR0cDovL2NybC1vY3NwOjgwODIvcmVzcG9uZGVyLzAqBggrBgEFBQcwAoYeaHR0cDovL2NybC1vY3NwL2Nlci9yb290Y2EuY2VyMB0GA1UdDgQWBBTZGXi4ipKMhd2CF8xK7B-qnPKjWDBqBgNVHREEYzBhoBsGCSpwAQIBAQEEAqAODAzQotCV0KHQotCQ0JKgGwYJKnABAgEBAQQDoA4MDNCh0K_QoNCT0JXQmaAlBgkqcAECAQEBBASgGAwW0JPQldCd0JDQlNCX0KzQldCS0IbQpzALBgNVHQ8EBAMCBeAwJQYDVR0gBB4wHDAMBgoqcAACACJlTgI8MAwGCipwAAIAImVPDAEwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMA0GCSpwAAIAImUtDAUAAzEAQI8uMxzTy9m0BfQWxfGzqz93KrX45Hbl41yxCH6H5TDiJKeEf03Yhw6NHuVXifJKMYIBgTCCAX0CAQEwgbwwgasxOzA5BgNVBAMeMgQgBDUEQQQ_BEMEMQQ7BDgEOgQwBD0EQQQ6BDgEOQAgBCMEJgAgACgEQgQ1BEEEQgApMV0wWwYDVQQKHlQEIAQjBB8AIAAiBB0EMARGBDgEPgQ9BDAEOwRMBD0ESwQ5ACAERgQ1BD0EQgRAACAETQQ7BDUEOgRCBEAEPgQ9BD0ESwRFACAEQwRBBDsEQwQzACIxDTALBgNVBAYeBABCAFkCDEDliVKQkYOiAAD3GDANBgkqcAACACJlH1EFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIyMDMxMTExMjgwNFowLwYJKoZIhvcNAQkEMSIEII2niPvQxX1Gmzkge2iV8AV3y3h3oUNywozfbZucSeElMA0GCSpwAAIAImUtDAUABDDTv39V02zcYHLCfsldY5zZqUxK8dN0CgV_lwN1TAUQ7cuQ58X_DFw4bGaJF7It56c)

My code for decode:
```rust
#[derive(AsnType, Decode, Encode)]
#[derive(Debug)]
struct StbStruct {
    oid: ObjectIdentifier,
    #[rasn(tag(0))]
    data: SequenceOf<SignedData>,
}
fn verify_cms(structure: &SignedData) -> bool {
    let data = structure.encap_content_info.content.as_ref().to_vec();

    let certset = structure.certificates.as_ref().unwrap();
    let mut key: Vec<u8> = vec![];
    for cert in certset {
        if let CertificateChoices::Certificate(c) = cert {
            key = c.tbs_certificate.subject_public_key_info.subject_public_key.clone().into_vec();
        }
    }
    let signersset = &structure.signer_infos;
    for signer in signersset {
        let mut signed_attrs = signer.signed_attrs.clone().unwrap();


        let mut signed_attrs_der = rasn::der::encode(&signed_attrs).unwrap();
        println!("{:02X?}", signed_attrs_der);
    }
    // correct setof from lapoit
    let mut signed_attrs_der = vec![
        0x31, 0x69, 0x30, 0x18, 0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09, 0x03, 0x31, 0x0B, 0x06, 0x09, 0x2A,     0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x07, 0x01,
        0x30, 0x1C, 0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09, 0x05, 0x31, 0x0F, 0x17, 0x0D, 0x32, 0x32, 0x30,     0x33, 0x31, 0x31, 0x31, 0x31, 0x32, 0x38, 0x30, 0x34, 0x5A,
        0x30, 0x2F, 0x06, 0x09, 0x2A, 0x86, 0x48, 0x86, 0xF7, 0x0D, 0x01, 0x09, 0x04, 0x31, 0x22, 0x04, 0x20, 0x8D, 0xA7, 0x88,     0xFB, 0xD0, 0xC5, 0x7D, 0x46, 0x9B, 0x39, 0x20, 0x7B, 0x68, 0x95, 0xF0, 0x05, 0x77, 0xCB, 0x78, 0x77, 0xA1, 0x43, 0x72, 0xC2, 0x8C, 0xDF, 0x6D, 0x9B, 0x9C, 0x49, 0xE1, 0x25
    ];
    println!("{:02X?}", signed_attrs_der);

    true
}
fn main() {
    let cms_bytes = base64::decode("MIIFlQYJK...").unwrap();
    let d: StbStruct = rasn::der::decode(&cms_bytes).unwrap();
    let signeddata = d.data.first().unwrap();
    println!("{:?}", verify_cms(&signeddata));
}

```

And from my decode i am getting sorted set:
```
[31, 69, 30, 18, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 03, 31, 0B, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 07, 01, 30, 2F, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 04, 31, 22, 04, 20, 8D, A7, 88, FB, D0, C5, 7D, 46, 9B, 39, 20, 7B, 68, 95, F0, 05, 77, CB, 78, 77, A1, 43, 72, C2, 8C, DF, 6D, 9B, 9C, 49, E1, 25, 30, 1C, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 05, 31, 0F, 17, 0D, 32, 32, 30, 33, 31, 31, 31, 31, 32, 38, 30, 34, 5A]
```

So, difference is:
```
My:
[31, 69, 30, 18, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 03, 31, 0B, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 07, 01, 30, 2F, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 04, 31, 22, 04, 20, 8D, A7, 88, FB, D0, C5, 7D, 46, 9B, 39, 20, 7B, 68, 95, F0, 05, 77, CB, 78, 77, A1, 43, 72, C2, 8C, DF, 6D, 9B, 9C, 49, E1, 25, 30, 1C, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 05, 31, 0F, 17, 0D, 32, 32, 30, 33, 31, 31, 31, 31, 32, 38, 30, 34, 5A]
"MWkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAvBgkqhkiG9w0BCQQxIgQgjaeI+9DFfUabOSB7aJXwBXfLeHehQ3LCjN9tm5xJ4SUwHAYJKoZIhvcNAQkFMQ8XDTIyMDMxMTExMjgwNFo="

Correct:
[31, 69, 30, 18, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 03, 31, 0B, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 07, 01, 30, 1C, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 05, 31, 0F, 17, 0D, 32, 32, 30, 33, 31, 31, 31, 31, 32, 38, 30, 34, 5A, 30, 2F, 06, 09, 2A, 86, 48, 86, F7, 0D, 01, 09, 04, 31, 22, 04, 20, 8D, A7, 88, FB, D0, C5, 7D, 46, 9B, 39, 20, 7B, 68, 95, F0, 05, 77, CB, 78, 77, A1, 43, 72, C2, 8C, DF, 6D, 9B, 9C, 49, E1, 25]
"MWkwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjIwMzExMTEyODA0WjAvBgkqhkiG9w0BCQQxIgQgjaeI+9DFfUabOSB7aJXwBXfLeHehQ3LCjN9tm5xJ4SU="

```

So there is a question, is there any way to get der structure without sorted values?
Correct der:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/5614215/158382267-0fbcae88-c83d-43f4-bd5e-4cfced4f1663.png">

My sorted der:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/5614215/158382319-70589d74-6df4-4d42-9d73-a31198b922d3.png">

**Comment by XAMPPRocky** [comment]
Thank you for your issue! However, I believe you are misinformed on the correct behaviour here, lapoit isn't verifying that this correct, only that it matches the BER TLV format. In order to be considered valid DER, `SET OF` types must be sorted, from X.690 11.6 (Restrictions on BER employed by both CER and DER):

> The encodings of the component values of a set-of value shall appear in ascending order, the encodings being compared as octet strings with the shorter components being padded at their trailing end with 0-octets.
>   NOTE – The padding octets are for comparison purposes only and do not appear in the encodings.

So whoever issued this certificate is using a malformed encoder (which is not uncommon), that is encoding `SET OF` types with BER's rules which do allow for unsorted `SET OF` types.

**Comment by makavity** [comment]
Sounds sadly :(
BY company, named NIITZI formed this cms and signed not sorted data. So, can't verify it normally.
Thanks for help.

**Comment by XAMPPRocky** [comment]
I'm going to close this as resolved, but feel to open a [discussion](https://github.com/XAMPPRocky/rasn/discussions) if you'd like to ask more stuff. Good luck with your project!
