### ISSUE TITLE
Treat newtypes as passthrough containers when encoding/decoding

### ISSUE THREAD

**Issue by orthecreedence** [XAMPPRocky/rasn#85]
Hello! I'm just starting to use this project and it's everything I want in a DER encoder/decoder (especially the derive macros, which are incredibly helpful). One thing I'm wondering if is there's a built-in way to have something like this:

```rust
#[derive(Debug, AsnType, Encode, Decode)]
struct SignatureWrapper(Bytes);

#[derive(Debug, AsnType, Encode, Decode)]
#[rasn(choice)]
enum Signature {
    #[rasn(tag(0))]
    Ed25519(SignatureWrapper),
}
```

And encode it as if `SignatureWrapper` was just a `Bytes`. Right now, it seems to wrap it. Is there a `#[rasn(...)]` attribute that can do this, or would this be something I'd need to open a PR for? Thank you!

**Comment by orthecreedence** [comment]
You know what, I don't think I need this actually. Since rust got `[u8; N]` const generic support I can just manually implement Encode/Decode for one type that covers everything. I'll leave it open in case you find it useful still, but if not, feel free to close.

**Comment by XAMPPRocky** [comment]
Thank you for your issue! This functionality is already available in `rasn`. Simply add `#[rasn(delegate)]` to the newtype, and then it will be transparently encoded.

**Comment by orthecreedence** [comment]
Oh, well how about that. That's great to know. Thanks!
