### ISSUE TITLE
BER Unable to encode Bitstring ending in 0x00

### ISSUE THREAD

**Issue by anthok** [XAMPPRocky/rasn#89]
I don't think it's currently possible to encode Bitstrings ending in `0x00`. I think that is due to this code https://github.com/XAMPPRocky/rasn/blob/1ff67d472faa3f0448d1b6ca31cd8c1b149ff072/src/ber/enc.rs#L259

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Yeah, should probably just remove that code, though I remember running into other issues without that, could no longer be relevant though.
