### ISSUE TITLE
rasn-pkix release for pr #84?

### ISSUE THREAD

**Issue by curtisleefulton** [XAMPPRocky/rasn#93]
Any chance we can get a release for rasn-pkix that includes pr #84? Latest for crates.io still has 0.5.2, which doesn't include https://github.com/XAMPPRocky/rasn/pull/84 . 

My devs will thank you :)

best,

Curtis

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I’ve released 0.6.0

**Comment by curtisleefulton** [comment]
thank you!
